gems: [jekyll-coffeescript, jekyll-watch, jekyll-assets]

gems:
   - jekyll-seo-tag

title: QIClib
description: A C++11 library for quantum information and computation based on Armadillo
url: https://titaschanda.github.io/QIClib
author: Titas Chanda
logo: qic.png